/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminInfo {
  'principal' : Principal,
  'username' : string,
  'role' : UserRole,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'createdAt' : Time,
  'size' : bigint,
  'updatedAt' : Time,
  'parentId' : [] | [string],
}
export interface FileMove {
  'id' : string,
  'isFolder' : boolean,
  'newParentId' : [] | [string],
}
export type FileSystemItem = { 'file' : FileMetadata } |
  { 'folder' : FolderMetadata };
export interface FolderMetadata {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'parentId' : [] | [string],
}
export interface FolderSearchResults {
  'files' : Array<FileMetadata>,
  'folders' : Array<FolderMetadata>,
}
export interface StorageStats {
  'frontendCanisterId' : string,
  'appVersion' : string,
  'totalStorageBytes' : bigint,
  'backendCanisterId' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFile' : ActorMethod<
    [string, string, bigint, [] | [string], ExternalBlob],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFolder' : ActorMethod<[string, [] | [string]], string>,
  'deleteFile' : ActorMethod<[string], boolean>,
  'deleteFolder' : ActorMethod<[string], boolean>,
  'getAllFolders' : ActorMethod<[], Array<FolderMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getFile' : ActorMethod<[string], [] | [FileMetadata]>,
  'getFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getFolder' : ActorMethod<[string], [] | [FolderMetadata]>,
  'getFolderContents' : ActorMethod<[[] | [string]], Array<FileSystemItem>>,
  'getMembers' : ActorMethod<[], Array<AdminInfo>>,
  'getStorageStats' : ActorMethod<[], StorageStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[], UserRole>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isUsernameUnique' : ActorMethod<[string], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'moveItem' : ActorMethod<[string, [] | [string], boolean], undefined>,
  'moveItems' : ActorMethod<[Array<FileMove>], undefined>,
  'removeMember' : ActorMethod<[Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchFiles' : ActorMethod<[string], Array<FileMetadata>>,
  'searchFoldersInSubtree' : ActorMethod<
    [string, [] | [string]],
    FolderSearchResults
  >,
  'searchSubtree' : ActorMethod<[string, [] | [string]], Array<FileSystemItem>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setBackendCanisterId' : ActorMethod<[string], undefined>,
  'setFrontendCanisterId' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];