/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const FolderMetadata = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'parentId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FileMetadata = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : Time,
  'size' : IDL.Nat,
  'updatedAt' : Time,
  'parentId' : IDL.Opt(IDL.Text),
});
export const FileSystemItem = IDL.Variant({
  'file' : FileMetadata,
  'folder' : FolderMetadata,
});
export const AdminInfo = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'role' : UserRole,
});
export const StorageStats = IDL.Record({
  'frontendCanisterId' : IDL.Text,
  'appVersion' : IDL.Text,
  'totalStorageBytes' : IDL.Nat,
  'backendCanisterId' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const FileMove = IDL.Record({
  'id' : IDL.Text,
  'isFolder' : IDL.Bool,
  'newParentId' : IDL.Opt(IDL.Text),
});
export const FolderSearchResults = IDL.Record({
  'files' : IDL.Vec(FileMetadata),
  'folders' : IDL.Vec(FolderMetadata),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), ExternalBlob],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFolder' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Text], []),
  'deleteFile' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteFolder' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllFolders' : IDL.Func([], [IDL.Vec(FolderMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
  'getFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getFolder' : IDL.Func([IDL.Text], [IDL.Opt(FolderMetadata)], ['query']),
  'getFolderContents' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(FileSystemItem)],
      ['query'],
    ),
  'getMembers' : IDL.Func([], [IDL.Vec(AdminInfo)], ['query']),
  'getStorageStats' : IDL.Func([], [StorageStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [UserRole], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernameUnique' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'moveItem' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text), IDL.Bool], [], []),
  'moveItems' : IDL.Func([IDL.Vec(FileMove)], [], []),
  'removeMember' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchFiles' : IDL.Func([IDL.Text], [IDL.Vec(FileMetadata)], ['query']),
  'searchFoldersInSubtree' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [FolderSearchResults],
      ['query'],
    ),
  'searchSubtree' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(FileSystemItem)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setBackendCanisterId' : IDL.Func([IDL.Text], [], []),
  'setFrontendCanisterId' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const FolderMetadata = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'parentId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FileMetadata = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Nat,
    'updatedAt' : Time,
    'parentId' : IDL.Opt(IDL.Text),
  });
  const FileSystemItem = IDL.Variant({
    'file' : FileMetadata,
    'folder' : FolderMetadata,
  });
  const AdminInfo = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'role' : UserRole,
  });
  const StorageStats = IDL.Record({
    'frontendCanisterId' : IDL.Text,
    'appVersion' : IDL.Text,
    'totalStorageBytes' : IDL.Nat,
    'backendCanisterId' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const FileMove = IDL.Record({
    'id' : IDL.Text,
    'isFolder' : IDL.Bool,
    'newParentId' : IDL.Opt(IDL.Text),
  });
  const FolderSearchResults = IDL.Record({
    'files' : IDL.Vec(FileMetadata),
    'folders' : IDL.Vec(FolderMetadata),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), ExternalBlob],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFolder' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Text], []),
    'deleteFile' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteFolder' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllFolders' : IDL.Func([], [IDL.Vec(FolderMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
    'getFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getFolder' : IDL.Func([IDL.Text], [IDL.Opt(FolderMetadata)], ['query']),
    'getFolderContents' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(FileSystemItem)],
        ['query'],
      ),
    'getMembers' : IDL.Func([], [IDL.Vec(AdminInfo)], ['query']),
    'getStorageStats' : IDL.Func([], [StorageStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [UserRole], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernameUnique' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'moveItem' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text), IDL.Bool], [], []),
    'moveItems' : IDL.Func([IDL.Vec(FileMove)], [], []),
    'removeMember' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchFiles' : IDL.Func([IDL.Text], [IDL.Vec(FileMetadata)], ['query']),
    'searchFoldersInSubtree' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [FolderSearchResults],
        ['query'],
      ),
    'searchSubtree' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(FileSystemItem)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setBackendCanisterId' : IDL.Func([IDL.Text], [], []),
    'setFrontendCanisterId' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };